@extends('Layouts.AdminLayout') 
@section('content')

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div class="flex justify-center items-center h-screen "> 
  <div class=" grid grid-cols-3  gap-x-10 ">
      {{-- Pie chart --}}
    <div class="max-w-sm w-full h-fit bg-white rounded-lg shadow-sm dark:bg-gray-800 p-4 md:p-6">

        <div class="flex justify-between items-start w-full">
            <div class="flex-col items-center">
              <div class="flex items-center mb-1">
                  <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white me-1">Groupes Diffrence</h5>
                  <svg data-popover-target="chart-info" data-popover-placement="bottom" class="w-3.5 h-3.5 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm0 16a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm1-5.034V12a1 1 0 0 1-2 0v-1.418a1 1 0 0 1 1.038-.999 1.436 1.436 0 0 0 1.488-1.441 1.501 1.501 0 1 0-3-.116.986.986 0 0 1-1.037.961 1 1 0 0 1-.96-1.037A3.5 3.5 0 1 1 11 11.466Z"/>
                  </svg>
                  <div data-popover id="chart-info" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-xs opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
                      <div class="p-3 space-y-2">
                          <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
                          <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
                          <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
                          <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
                          <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read more <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg></a>
                  </div>
                  <div data-popper-arrow></div>
              </div>
            </div>
            <div id="dateRangeDropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow-sm w-80 lg:w-96 dark:bg-gray-700 dark:divide-gray-600">
                <div class="p-3" aria-labelledby="dateRangeButton">
                  <div date-rangepicker datepicker-autohide class="flex items-center">
                      <div class="relative">
                        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                              <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                            </svg>
                        </div>
                        <input name="start" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Start date">
                      </div>
                      <span class="mx-2 text-gray-500 dark:text-gray-400">to</span>
                      <div class="relative">
                        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                              <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                            </svg>
                        </div>
                        <input name="end" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="End date">
                    </div>
                  </div>
                </div>
            </div>
          </div>
          <div class="flex justify-end items-center">
            </button>
         
        </div>
        </div>
      
        <div class="py-6" id="pie-chart"></div>
      
      </div> 
        {{-- linear chart  --}}
<div class="max-w-sm w-full bg-white rounded-lg shadow-sm dark:bg-gray-800 p-4 md:p-6">
  <div class="flex justify-between">
    <div>
      <h5  id='total-users' class="leading-none text-3xl font-bold text-gray-900 dark:text-white pb-2"></h5>
      <p class="text-base font-normal text-gray-500 dark:text-gray-400">Users this week</p>
    </div>
    <div
      class="flex items-center px-2.5 py-0.5 text-base font-semibold text-green-500 dark:text-green-500 text-center">
      12%
      <svg class="w-3 h-3 ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13V1m0 0L1 5m4-4 4 4"/>
      </svg>
    </div>
  </div>
  <div id="area-chart"></div>

</div>
 <div class="">
        
<form class="max-w-sm mx-auto" method="POST" action="{{route('todolist.store')}}"> 
  @csrf
  <label for="email-address-icon" class="block mb-2 text-lg font-medium text-gray-900 dark:text-white">Todo Liste</label>
  <div class="relative">
    <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
      <i class="fa-solid fa-list-check"></i>
      {{-- <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"> --}}
        <path d="m10.036 8.278 9.258-7.79A1.979 1.979 0 0 0 18 0H2A1.987 1.987 0 0 0 .641.541l9.395 7.737Z"/>
        <path d="M11.241 9.817c-.36.275-.801.425-1.255.427-.428 0-.845-.138-1.187-.395L0 2.6V14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2.5l-8.759 7.317Z"/>
      </svg>
    </div>
    <div class="flex justify-center items-center gap-1">
      <input type="text" id="email-address-icon" name="task" required class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="new task">
      <button type="submit" class="text-white mt-2 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Add </button>
    </div>
  </form>
  
  </div>
  <ul class="max-w-md space-y-1 text-gray-500 list-inside dark:text-gray-400">
    @foreach ( $tasks as $task) 
    @if ($task->status == 'pending')
    <li class="flex items-center flex-row relative">
      <form  class="flex items-center justify-center" action="{{route('todolist.update',$task)}}" method="POST">
        @method("PUT")
        @csrf
        <button type="submit" class="hover:cursor-pointer">
          <svg class="w-3.5 h-3.5 me-2 text-gray-500 dark:text-gray-400 shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
         </svg>
        </button>
       
      </form>
       <p> {{$task->body}}
      </p>  
      <form action="{{route("todolist.destroy",$task)}}" method="POST">
        @csrf
        @method("DELETE")
        <button class="hover:cursor-pointer">
          <i class="fa-solid fa-trash text-red-600  absolute right-0"></i>
        </button>
      </form>
 
  </li>
    @else
    <li class="flex items-center relative">
      <form  class="flex items-center justify-center" action="{{route('todolist.update',$task)}}" method="POST">
        @method("PUT")
        @csrf
        <button type="submit" class="hover:cursor-pointer">
          <svg class="w-3.5 h-3.5 me-2 text-green-500 dark:text-green-400 shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
         </svg>
        </button>
       
      </form>
       <p class="line-through decoration-green-500 decoration-2"> {{$task->body}}
      </p>   
      <form action="{{route("todolist.destroy",$task)}}" method="POST">
        @csrf
        @method("DELETE")


        <button class="hover:cursor-pointer">
          <i class="fa-solid fa-trash text-red-600  absolute right-0"></i>
        </button>
      </form>
  </li>
    @endif
    
    @endforeach
   
</ul>
<div class="mt-5">
<div class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700">
  <i class="fa-solid fa-graduation-cap w-7 h-7 text-4xl text-gray-500"></i>
  <a href="#">
      <h5 class="mb-2 text-2xl font-semibold tracking-tight text-gray-900 dark:text-white" >{{$studentsCount}} Active Student</h5>
  </a>
  <p class="mb-3 font-normal text-gray-500 dark:text-gray-400">Go to the link to view the students list as an admin. It's recommended to remain active:</p>
  <a href="{{route('admin.studentList')}}" class="inline-flex font-medium items-center text-blue-600 hover:underline">
      See student list
      <svg class="w-3 h-3 ms-2.5 rtl:rotate-[270deg]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11v4.833A1.166 1.166 0 0 1 13.833 17H2.167A1.167 1.167 0 0 1 1 15.833V4.167A1.166 1.166 0 0 1 2.167 3h4.618m4.447-2H17v5.768M9.111 8.889l7.778-7.778"/>
      </svg>
  </a>
</div>

</div>
      </div>
      
    </div>

       <script>
                const groupesData = <?php echo json_encode($result); ?> ;
                // console.log( "real data" , results); 
                // console.log("group data" , groupesData); 
                const groupNames = groupesData.map(item => item.group_name);
                const groupCounts = groupesData.map(item => item.count); 
                console.log(groupNames);
                console.log(groupCounts);
        // console.log(groupesData);
    const getChartOptions = () => {
      return {
        series: groupCounts, 
        colors: ["#1C64F2", "#16BDCA", "#9061F9" , "#F1B44C"],
        chart: {
          height: 420,
          width: "100%",
          type: "pie",
        },
        stroke: {
          colors: ["white"],
          lineCap: "",
        },
        plotOptions: {
          pie: {
            labels: {
              show: true,
            },
            size: "100%",
            dataLabels: {
              offset: -25
            }
          },
        },
        labels:groupNames,
        dataLabels: {
          enabled: true,
          style: {
            fontFamily: "Inter, sans-serif",
          },
        },
        legend: {
          position: "bottom",
          fontFamily: "Inter, sans-serif",
        },
        yaxis: {
          labels: {
            formatter: function (value) {
              return value + "%"
            },
          },
        },
        xaxis: {
          labels: {
            formatter: function (value) {
              return value  + "%"
            },
          },
          axisTicks: {
            show: false,
          },
          axisBorder: {
            show: false,
          },
        },
      }
    }
    
    if (document.getElementById("pie-chart") && typeof ApexCharts !== 'undefined') {
      const chart = new ApexCharts(document.getElementById("pie-chart"), getChartOptions());
      chart.render();
    }

    const usersData = <?php echo json_encode($users); ?>;
console.log("users data", usersData);

// Extract dates and user counts
const categories = usersData.map(item => item.created_date);
const data = usersData.map(item => item.user_count);

const options = {
  chart: {
    height: "100%",
    maxWidth: "100%",
    type: "area",
    fontFamily: "Inter, sans-serif",
    dropShadow: {
      enabled: false,
    },
    toolbar: {
      show: false,
    },
  },
  tooltip: {
    enabled: true,
    theme: "dark", // Ensures tooltip matches dark mode
    style: {
      fontSize: "12px",
      fontFamily: "Inter, sans-serif",
    },
    y: {
      formatter: function (val) {
        return val + " users"; // Ensures correct label format
      },
    },
    background: "#1E293B", // Dark gray background
    borderRadius: 4,
    x: {
      show: true,
    },
  },
  fill: {
    type: "gradient",
    gradient: {
      opacityFrom: 0.55,
      opacityTo: 0,
      shade: "#1C64F2",
      gradientToColors: ["#1C64F2"],
    },
  },
  dataLabels: {
    enabled: false,
  },
  stroke: {
    width: 6,
  },
  grid: {
    show: false,
    strokeDashArray: 4,
    padding: {
      left: 2,
      right: 2,
      top: 0
    },
  },
  series: [
    {
      name: "New users",
      data: data,  // Updated with real data
      color: "#1A56DB",
    },
  ],
  xaxis: {
    categories: categories,  // Updated with real dates
    labels: {
      show: true,
    },
    axisBorder: {
      show: false,
    },
    axisTicks: {
      show: false,
    },
  },
  yaxis: {
    show: true,
  },
};

if (document.getElementById("area-chart") && typeof ApexCharts !== 'undefined') {
  const chart = new ApexCharts(document.getElementById("area-chart"), options);
  chart.render();
} 
  const totleUsers = usersData.reduce((total, item) => total + item.user_count, 0); 
  console.log(totleUsers); 
  document.getElementById("total-users").textContent = totleUsers ;
  // document.getElementById('active-students').textContent = totleUsers + " Active Students";
       </script>
    
</div>
@endsection